In [1]:
import pandas as pd

In [2]:
raw_df = pd.read_csv("data/raw/final_annotated_1000_records_data_merged.csv")
raw_df.head()

,video_id,video_title,author,comment,likes,published_at,category,sentiment,sentiment_numeric,Unnamed: 9,claude_sentiment,gemini_sentiment,chatgpt_sentiment,majority_vote_final
0,PghQPGacrlI,Best SUVs tested: BMW v Porsche v Mercedes v A...,@carwow,Sell your car for free with Carwow: https://bi...,133,2024-07-29T10:12:23Z,suv,positive,1,NaN,neutral,positive,neutral,NaN
1,PghQPGacrlI,Best SUVs tested: BMW v Porsche v Mercedes v A...,@silvanelsire5971,wheres xc90,0,2026-03-17T08:23:53Z,suv,neutral,0,NaN,neutral,neutral,neutral,neutral
2,PghQPGacrlI,Best SUVs tested: BMW v Porsche v Mercedes v A...,@kingofthebridge8339,Land cruiser is better than all of them.,0,2026-03-12T20:49:12Z,suv,positive,1,NaN,positive,positive,neutral,positive
3,PghQPGacrlI,Best SUVs tested: BMW v Porsche v Mercedes v A...,@andrescardonagutierrez6732,Where’s the Volvo xC90,0,2026-03-04T21:58:20Z,suv,neutral,0,NaN,neutral,neutral,neutral,neutral
4,PghQPGacrlI,Best SUVs tested: BMW v Porsche v Mercedes v A...,@johns8702,I can see u only praise bmw .. not good,0,2026-02-25T04:19:54Z,suv,negative,2,NaN,negative,negative,neutral,negative

In [3]:
print(raw_df["Unnamed: 9"].isna().count())
raw_df.info()

1004
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             1004 non-null   object
 1   video_title          1004 non-null   object
 2   author               1004 non-null   object
 3   comment              1003 non-null   object
 4   likes                1004 non-null   int64
 5   published_at         1004 non-null   object
 6   category             1004 non-null   object
 7   sentiment            1004 non-null   object
 8   sentiment_numeric    1004 non-null   int64
 9   Unnamed: 9           0 non-null      float64
 10  claude_sentiment     1000 non-null   object
 11  gemini_sentiment     1000 non-null   object
 12  chatgpt_sentiment    998 non-null    object
 13  majority_vote_final  835 non-null    object
dtypes: float64(1), int64(2), object(11)
memory usage: 109.9+ KB

In [4]:
imp_df = raw_df[["comment","sentiment","claude_sentiment","gemini_sentiment","chatgpt_sentiment","majority_vote_final"]]
imp_df['index'] = imp_df.index
imp_df.head()

C:\Users\yasmi\AppData\Local\Temp\ipykernel_27768\1964929336.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_df['index'] = imp_df.index

,comment,sentiment,claude_sentiment,gemini_sentiment,chatgpt_sentiment,majority_vote_final,index
0,Sell your car for free with Carwow: https://bi...,positive,neutral,positive,neutral,NaN,0
1,wheres xc90,neutral,neutral,neutral,neutral,neutral,1
2,Land cruiser is better than all of them.,positive,positive,positive,neutral,positive,2
3,Where’s the Volvo xC90,neutral,neutral,neutral,neutral,neutral,3
4,I can see u only praise bmw .. not good,negative,negative,negative,neutral,negative,4

In [15]:
rows_with_nan = imp_df[imp_df.isna().any(axis=1)]
rows_with_nan

,comment,sentiment,claude_sentiment,gemini_sentiment,chatgpt_sentiment,majority_vote_final,index
0,Sell your car for free with Carwow: https://bi...,positive,neutral,positive,neutral,NaN,0
5,You said the Audi is better then the Mercedes ...,positive,neutral,positive,neutral,NaN,5
10,Id rather buy a flat,neutral,negative,neutral,negative,NaN,10
26,Is it me or do they all look bland?,negative,negative,neutral,neutral,NaN,26
38,How do people afford a 100grand suv? Am I just...,negative,neutral,negative,neutral,NaN,38
...,...,...,...,...,...,...,...
999,"The Audi Q8 won, because.",neutral,neutral,neutral,NaN,neutral,999
1000,Why did they remove the night vision part,unknown,NaN,NaN,NaN,NaN,1000
1001,Easy: \n1) touareg - price/value\n2) porsche -...,unknown,NaN,NaN,NaN,NaN,1001
1002,strange that BMW's win every time...lmao,unknown,NaN,NaN,NaN,NaN,1002
1003,I will never choose anything over the x5,unknown,NaN,NaN,NaN,NaN,1003

In [17]:
rows_with_nan.to_csv("rows_with_nan.csv", index=False)
print("Saved rows_with_nan.csv - open it in VS Code for interactive table viewer")

Saved rows_with_nan.csv - open it in VS Code for interactive table viewer

In [5]:
edited_df = pd.read_csv("manually_filled_in.csv")

mapping = dict(zip(edited_df['index'], edited_df['majority_vote_final']))

imp_df['majority_vote_final'] = imp_df['index'].map(mapping).fillna(imp_df['majority_vote_final'])

print(f"Updated {len(mapping)} rows")
print("\nRows that were filled:")
updated_rows = imp_df[imp_df['index'].isin(mapping.keys())]
updated_rows

Updated 172 rows

Rows that were filled:

C:\Users\yasmi\AppData\Local\Temp\ipykernel_27768\2831165654.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_df['majority_vote_final'] = imp_df['index'].map(mapping).fillna(imp_df['majority_vote_final'])

,comment,sentiment,claude_sentiment,gemini_sentiment,chatgpt_sentiment,majority_vote_final,index
0,Sell your car for free with Carwow: https://bi...,positive,neutral,positive,neutral,neutral,0
5,You said the Audi is better then the Mercedes ...,positive,neutral,positive,neutral,neutral,5
10,Id rather buy a flat,neutral,negative,neutral,negative,negative,10
26,Is it me or do they all look bland?,negative,negative,neutral,neutral,negative,26
38,How do people afford a 100grand suv? Am I just...,negative,neutral,negative,neutral,neutral,38
...,...,...,...,...,...,...,...
999,"The Audi Q8 won, because.",neutral,neutral,neutral,NaN,positive,999
1000,Why did they remove the night vision part,unknown,NaN,NaN,NaN,neutral,1000
1001,Easy: \n1) touareg - price/value\n2) porsche -...,unknown,NaN,NaN,NaN,neutral,1001
1002,strange that BMW's win every time...lmao,unknown,NaN,NaN,NaN,negtaive,1002
1003,I will never choose anything over the x5,unknown,NaN,NaN,NaN,negative,1003

In [6]:
rows_with_nan = imp_df[imp_df["majority_vote_final"].isna()]
rows_with_nan

Empty DataFrame
Columns: [comment, sentiment, claude_sentiment, gemini_sentiment, chatgpt_sentiment, majority_vote_final, index]
Index: []

In [7]:
rows_with_nan = imp_df[imp_df.isna().any(axis=1)]
rows_with_nan

,comment,sentiment,claude_sentiment,gemini_sentiment,chatgpt_sentiment,majority_vote_final,index
90,"""Have they made it from scrotums?"" ��",neutral,positive,neutral,NaN,neutral,90
248,NaN,neutral,neutral,neutral,neutral,neutral,248
999,"The Audi Q8 won, because.",neutral,neutral,neutral,NaN,positive,999
1000,Why did they remove the night vision part,unknown,NaN,NaN,NaN,neutral,1000
1001,Easy: \n1) touareg - price/value\n2) porsche -...,unknown,NaN,NaN,NaN,neutral,1001
1002,strange that BMW's win every time...lmao,unknown,NaN,NaN,NaN,negtaive,1002
1003,I will never choose anything over the x5,unknown,NaN,NaN,NaN,negative,1003

In [8]:
imp_df_extracted = imp_df[["comment","majority_vote_final","index"]]
imp_df_extracted.head()

,comment,majority_vote_final,index
0,Sell your car for free with Carwow: https://bi...,neutral,0
1,wheres xc90,neutral,1
2,Land cruiser is better than all of them.,positive,2
3,Where’s the Volvo xC90,neutral,3
4,I can see u only praise bmw .. not good,negative,4

now that rows are fully annotated, now schemes

scheme1: all methods in clean.py except : replace_emojis_and_punctuations

In [11]:
import os
import sys

sys.path.append("clean data")

from clean import clean_text

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\yasmi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\yasmi\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [15]:
imp_df_extracted['clean_comment'] = imp_df_extracted['comment'].astype(str).apply(
    lambda x: clean_text(
        x,
        remove_special=True,
        clean_emojis=False,
        drop_emojis=True,
        lowercase=True,
        correct_spelling=False,
        lemmatize=True,
        remove_stops=True
    )
)

C:\Users\yasmi\AppData\Local\Temp\ipykernel_27768\3395502975.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_df_extracted['clean_comment'] = imp_df_extracted['comment'].astype(str).apply(

In [16]:
output_path = "data/scheme1/cleaned_comments1.csv"
os.makedirs(os.path.dirname(output_path), exist_ok=True)

imp_df_extracted.to_csv(output_path, index=False, encoding="utf-8")

print(f"Saved to {output_path}")

Saved to data/scheme1/cleaned_comments1.csv

In [18]:
imp_df_extracted['clean_comment'] = imp_df_extracted['comment'].astype(str).apply(
    lambda x: clean_text(
        x,
        remove_special=True,
        clean_emojis=True,
        drop_emojis=False,
        lowercase=True,
        correct_spelling=False,
        lemmatize=True,
        remove_stops=True
    )
)

output_path = "data/scheme2/cleaned_comments2.csv"
os.makedirs(os.path.dirname(output_path), exist_ok=True)

imp_df_extracted.to_csv(output_path, index=False, encoding="utf-8")

print(f"Saved to {output_path}")

Saved to data/scheme2/cleaned_comments2.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_27768\4194875322.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_df_extracted['clean_comment'] = imp_df_extracted['comment'].astype(str).apply(

In [20]:
imp_df_extracted['clean_comment'] = imp_df_extracted['comment'].astype(str).apply(
    lambda x: clean_text(
        x,
        remove_special=True,
        clean_emojis=True,
        drop_emojis=False,
        lowercase=True,
        correct_spelling=False,
        lemmatize=False,
        remove_stops=True
    )
)

output_path = "data/scheme3/cleaned_comments3.csv"
os.makedirs(os.path.dirname(output_path), exist_ok=True)

imp_df_extracted.to_csv(output_path, index=False, encoding="utf-8")

print(f"Saved to {output_path}")

Saved to data/scheme3/cleaned_comments3.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_27768\3474015185.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imp_df_extracted['clean_comment'] = imp_df_extracted['comment'].astype(str).apply(

In [22]:
def preprocess_scheme1(text):
    return clean_text(
        str(text),
        remove_special=True,
        clean_emojis=False,
        drop_emojis=True,
        lowercase=True,
        correct_spelling=False,
        lemmatize=True,
        remove_stops=True
    )
    
    
def preprocess_scheme2(text):
    return clean_text(
        str(text),
        remove_special=True,
        clean_emojis=True,
        drop_emojis=False,
        lowercase=True,
        correct_spelling=False,
        lemmatize=True,
        remove_stops=True
    )


def preprocess_scheme3(text):
    return clean_text(
        str(text),
        remove_special=True,
        clean_emojis=True,
        drop_emojis=False,
        lowercase=True,
        correct_spelling=False,
        lemmatize=False,
        remove_stops=True
    )

In [24]:
imp_df_extracted[["comment","majority_vote_final","index"]].to_csv("data/raw/edited_null_annotation.csv")

text processing next

In [34]:
import subprocess

schemes = [
    ("scheme1", "data/scheme1/cleaned_comments1.csv"),
    ("scheme2", "data/scheme2/cleaned_comments2.csv"),
    ("scheme3", "data/scheme3/cleaned_comments3.csv"),
]

for scheme_name, input_path in schemes:
    print(f"\nProcessing {scheme_name}...")

    result = subprocess.run(
        [
            "python",
            "text processing/text_representati.py",
            "--input", input_path,
            "--output_prefix", scheme_name
        ],
        capture_output=True,
        text=True
    )
    
    print("STDOUT:\n", result.stdout)
    print("STDERR:\n", result.stderr)

    if result.returncode != 0:
        raise Exception(f"{scheme_name} failed")

print("\nExporting to CSV...")

result = subprocess.run(
    ["python", "text processing/export_to_csv.py"],
    capture_output=True,
    text=True
)

print("STDOUT:\n", result.stdout)
print("STDERR:\n", result.stderr)

if result.returncode != 0:
    raise Exception("Export failed")

Processing scheme1...
STDOUT:
 Loading data from data/scheme1/cleaned_comments1.csv...
Generating Bag-of-Words (BoW) for scheme1...
BoW saved to representations\scheme1_bow.npz (Shape: (1004, 2077))
Vocabulary saved to representations\scheme1_vocab.txt
Loading GloVe embeddings from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\text processing\..\data\glove.6B.100d.txt...
Loaded 400000 word vectors.
Generating GloVe average representations...
GloVe representations saved to representations\scheme1_glove.npy (Shape: (1004, 100))
Representation for scheme1 complete

STDERR:


Processing scheme2...
STDOUT:
 Loading data from data/scheme2/cleaned_comments2.csv...
Generating Bag-of-Words (BoW) for scheme2...
BoW saved to representations\scheme2_bow.npz (Shape: (1004, 2099))
Vocabulary saved to representations\scheme2_vocab.txt
Loading GloVe embeddings from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\text processing\..\data\glove.6B.100d.txt...
Loaded 400000 word vectors.
Generating GloVe average representations...
GloVe representations saved to representations\scheme2_glove.npy (Shape: (1004, 100))
Representation for scheme2 complete

STDERR:


Processing scheme3...
STDOUT:
 Loading data from data/scheme3/cleaned_comments3.csv...
Generating Bag-of-Words (BoW) for scheme3...
BoW saved to representations\scheme3_bow.npz (Shape: (1004, 2373))
Vocabulary saved to representations\scheme3_vocab.txt
Loading GloVe embeddings from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\text processing\..\data\glove.6B.100d.txt...
Loaded 400000 word vectors.
Generating GloVe average representations...
GloVe representations saved to representations\scheme3_glove.npy (Shape: (1004, 100))
Representation for scheme3 complete

STDERR:


Exporting to CSV...
STDOUT:

Processing scheme1...
Exporting full GloVe from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\representations\scheme1_glove.npy to c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme1\scheme1_glove.csv...
GloVe CSV saved: c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme1\scheme1_glove.csv (Shape: (1004, 100))
Exporting full BoW from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\representations\scheme1_bow.npz to c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme1\scheme1_bow.csv...
BoW CSV saved: c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme1\scheme1_bow.csv (Shape: (1004, 2077))

Processing scheme2...
Exporting full GloVe from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\representations\scheme2_glove.npy to c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme2\scheme2_glove.csv...
GloVe CSV saved: c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme2\scheme2_glove.csv (Shape: (1004, 100))
Exporting full BoW from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\representations\scheme2_bow.npz to c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme2\scheme2_bow.csv...
BoW CSV saved: c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme2\scheme2_bow.csv (Shape: (1004, 2099))

Processing scheme3...
Exporting full GloVe from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\representations\scheme3_glove.npy to c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme3\scheme3_glove.csv...
GloVe CSV saved: c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme3\scheme3_glove.csv (Shape: (1004, 100))
Exporting full BoW from c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\representations\scheme3_bow.npz to c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme3\scheme3_bow.csv...
BoW CSV saved: c:\Users\yasmi\Documents\College\Social Data Analytics\newTrial\data\scheme3\scheme3_bow.csv (Shape: (1004, 2373))

STDERR:

attaching labels to schemes

In [35]:
import pandas as pd

dataset = {
    "scheme1_bow_model": "data/scheme1/scheme1_bow.csv",
    "scheme2_bow_model": "data/scheme2/scheme2_bow.csv",
    "scheme3_bow_model": "data/scheme3/scheme3_bow.csv",
    "scheme1_glove_model": "data/scheme1/scheme1_glove.csv",
    "scheme2_glove_model": "data/scheme2/scheme2_glove.csv",
    "scheme3_glove_model": "data/scheme3/scheme3_glove.csv",
}

def attach_labels_to_datasets(dataset_dict, labels_series, label_col="majority_vote_final"):
    print("Attaching labels to datasets...")

    labels = labels_series.values

    for name, path in dataset_dict.items():
        print(f"\nProcessing {name} -> {path}")

        df = pd.read_csv(path)

        if len(df) != len(labels):
            raise ValueError(
                f"Row mismatch in {name}: dataset={len(df)} vs labels={len(labels)}"
            )

        df[label_col] = labels

        out_path = path.replace(".csv", "_labeled.csv")
        df.to_csv(out_path, index=False)

        print(f"Saved: {out_path}")
if __name__ == "__main__":

    labels = imp_df_extracted["majority_vote_final"]

    attach_labels_to_datasets(dataset, labels)

Attaching labels to datasets...

Processing scheme1_bow_model -> data/scheme1/scheme1_bow.csv
Saved: data/scheme1/scheme1_bow_labeled.csv

Processing scheme2_bow_model -> data/scheme2/scheme2_bow.csv
Saved: data/scheme2/scheme2_bow_labeled.csv

Processing scheme3_bow_model -> data/scheme3/scheme3_bow.csv
Saved: data/scheme3/scheme3_bow_labeled.csv

Processing scheme1_glove_model -> data/scheme1/scheme1_glove.csv
Saved: data/scheme1/scheme1_glove_labeled.csv

Processing scheme2_glove_model -> data/scheme2/scheme2_glove.csv
Saved: data/scheme2/scheme2_glove_labeled.csv

Processing scheme3_glove_model -> data/scheme3/scheme3_glove.csv
Saved: data/scheme3/scheme3_glove_labeled.csv

now modeling on the first models file

In [39]:
import subprocess
import os

os.makedirs("results", exist_ok=True)

script_path = "modeling/old_models.py"
output_file = "results/old_models_results2.txt"

result = subprocess.run(
    ["python", script_path],
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace"
)

with open(output_file, "w", encoding="utf-8") as f:
    f.write("===== STDOUT =====\n")
    f.write(result.stdout)
    f.write("\n\n===== STDERR =====\n")
    f.write(result.stderr)

print(f"Done. Results saved to {output_file}")

if result.returncode != 0:
    print("Script failed. Check STDERR inside the file.")

Done. Results saved to results/old_models_results2.txt

In [41]:
os.makedirs("results", exist_ok=True)

script_path = "modeling/modelsf1.py"
output_file = "results/optimized_models_results2.txt"

result = subprocess.run(
    ["python", script_path],
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace"
)

with open(output_file, "w", encoding="utf-8") as f:
    f.write("===== STDOUT =====\n")
    f.write(result.stdout)
    f.write("\n\n===== STDERR =====\n")
    f.write(result.stderr)

print(f"Done. Results saved to {output_file}")

if result.returncode != 0:
    print("Script failed. Check STDERR inside the file.")

Done. Results saved to results/optimized_models_results2.txt

In [43]:
import pandas as pd
import nltk
from nltk.corpus import sentiwordnet as swn
from nltk.corpus import wordnet as wn
from nltk.tokenize import word_tokenize
import os

nltk.download('punkt')
nltk.download('sentiwordnet')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')


class BingLiuClassifier:
    def __init__(self, pos_file, neg_file):
        self.pos_words = self._load_lexicon(pos_file)
        self.neg_words = self._load_lexicon(neg_file)
        self.negation_words = {
            "not", "no", "never", "n't", "hardly",
            "barely", "neither", "nor", "none"
        }

    def _load_lexicon(self, file_path):
        words = set()
        with open(file_path, 'r', encoding='iso-8859-1') as f:
            for line in f:
                if not line.startswith(';') and line.strip():
                    words.add(line.strip().lower())
        return words

    def analyze(self, text):
        if pd.isna(text):
            return "Neutral"

        tokens = word_tokenize(str(text).lower())
        score = 0

        for i, word in enumerate(tokens):
            sentiment = 0

            if word in self.pos_words:
                sentiment = 1
            elif word in self.neg_words:
                sentiment = -1

            if i > 0 and tokens[i - 1] in self.negation_words:
                sentiment *= -1

            score += sentiment

        return "Positive" if score > 0 else "Negative" if score < 0 else "Neutral"

class SentiWordNetClassifier:
    def get_wordnet_pos(self, tag):
        if tag.startswith('J'):
            return wn.ADJ
        elif tag.startswith('V'):
            return wn.VERB
        elif tag.startswith('N'):
            return wn.NOUN
        elif tag.startswith('R'):
            return wn.ADV
        return None

    def analyze(self, text):
        if pd.isna(text):
            return "Neutral"

        tokens = word_tokenize(str(text))
        tagged = nltk.pos_tag(tokens)

        score = 0

        for word, tag in tagged:
            wn_tag = self.get_wordnet_pos(tag)
            if wn_tag:
                synsets = list(swn.senti_synsets(word, wn_tag))
                if synsets:
                    s = synsets[0]
                    score += (s.pos_score() - s.neg_score())

        if score > 0.01:
            return "Positive"
        elif score < -0.01:
            return "Negative"
        return "Neutral"

def run_all_schemes():

    datasets = {
        "scheme1": "data/scheme1/cleaned_comments1.csv",
        "scheme2": "data/scheme2/cleaned_comments2.csv",
        "scheme3": "data/scheme3/cleaned_comments3.csv",
    }

    positive_lex = "positive-words.txt"
    negative_lex = "negative-words.txt"

    bing = BingLiuClassifier(positive_lex, negative_lex)
    swn_model = SentiWordNetClassifier()

    for scheme, input_file in datasets.items():
        print(f"\nProcessing {scheme}...")

        if not os.path.exists(input_file):
            print(f"Missing file: {input_file}")
            continue

        df = pd.read_csv(input_file)

        if "clean_comment" not in df.columns:
            print(f"Skipping {scheme}: no clean_comment column")
            continue

        df["clean_comment"] = df["clean_comment"].fillna("").astype(str)

        print("Running Bing Liu...")
        df["bing_liu_label"] = df["clean_comment"].apply(bing.analyze)

        print("Running SentiWordNet...")
        df["sentiwordnet_label"] = df["clean_comment"].apply(swn_model.analyze)

        output_file = f"data/{scheme}/{scheme}_lexical_labeled.csv"
        df.to_csv(output_file, index=False)

        print(f"Saved → {output_file}")

if __name__ == "__main__":
    run_all_schemes()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\yasmi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package sentiwordnet to
[nltk_data]     C:\Users\yasmi\AppData\Roaming\nltk_data...
[nltk_data]   Package sentiwordnet is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\yasmi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\yasmi\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Processing scheme1...
Running Bing Liu...
Running SentiWordNet...
Saved → data/scheme1/scheme1_lexical_labeled.csv

Processing scheme2...
Running Bing Liu...
Running SentiWordNet...
Saved → data/scheme2/scheme2_lexical_labeled.csv

Processing scheme3...
Running Bing Liu...
Running SentiWordNet...
Saved → data/scheme3/scheme3_lexical_labeled.csv

In [47]:
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

datasets = [
    "data/scheme1/scheme1_lexical_labeled.csv",
    "data/scheme2/scheme2_lexical_labeled.csv",
    "data/scheme3/scheme3_lexical_labeled.csv"
]

results = []

for path in datasets:

    df = pd.read_csv(path)

    scheme_name = path.split("/")[-1].replace("_lexical_labeled.csv", "")

    y_true = df["majority_vote_final"].astype(str).str.lower().str.strip()
    y_true = y_true.replace({"negtaive": "negative"})
    y_pred_blu = df["bing_liu_label"].astype(str).str.lower().str.strip()
    y_pred_senti = df["sentiwordnet_label"].astype(str).str.lower().str.strip()

    print(f"\n{scheme_name}")
    print("TRUE LABELS:", y_true.unique())
    print("PRED LABELS blu:", y_pred_blu.unique())
    print("PRED LABELS senti:", y_pred_senti.unique())

    f1_blu = f1_score(y_true, y_pred_blu, average="weighted")
    acc_blu = accuracy_score(y_true, y_pred_blu)
    cm_blu = confusion_matrix(y_true, y_pred_blu)

    results.append({
        "scheme": scheme_name,
        "model": "BingLiu",
        "f1": f1_blu,
        "accuracy": acc_blu,
        "confusion_matrix": cm_blu
    })

    f1_senti = f1_score(y_true, y_pred_senti, average="weighted")
    acc_senti = accuracy_score(y_true, y_pred_senti)
    cm_senti = confusion_matrix(y_true, y_pred_senti)

    results.append({
        "scheme": scheme_name,
        "model": "SentiWordNet",
        "f1": f1_senti,
        "accuracy": acc_senti,
        "confusion_matrix": cm_senti
    })

output_path = "results/lexical_models_report.txt"

with open(output_path, "w", encoding="utf-8") as f:
    f.write("LEXICAL MODELS BENCHMARK REPORT\n")
    f.write("=" * 60 + "\n\n")

    for r in results:
        f.write(f"Scheme: {r['scheme']}\n")
        f.write(f"Model: {r['model']}\n")
        f.write(f"F1 Score (weighted): {r['f1']:.4f}\n")
        f.write(f"Accuracy: {r['accuracy']:.4f}\n")
        f.write("Confusion Matrix:\n")
        f.write(str(r["confusion_matrix"]))
        f.write("\n" + "-" * 50 + "\n\n")

print(f"Saved report to: {output_path}")

scheme1
TRUE LABELS: ['neutral' 'positive' 'negative']
PRED LABELS blu: ['positive' 'neutral' 'negative']
PRED LABELS senti: ['positive' 'neutral' 'negative']

scheme2
TRUE LABELS: ['neutral' 'positive' 'negative']
PRED LABELS blu: ['positive' 'neutral' 'negative']
PRED LABELS senti: ['positive' 'neutral' 'negative']

scheme3
TRUE LABELS: ['neutral' 'positive' 'negative']
PRED LABELS blu: ['positive' 'neutral' 'negative']
PRED LABELS senti: ['positive' 'neutral' 'negative']
Saved report to: results/lexical_models_report.txt